Repository bcgov/rsbc-dmf, pull requests merged in 2020-02, with the labels that each got.

#4 DMFT-229, DMFT-231, DMFT-232 implemented. Added AbstractController, l…
  DMFT/pom.xml
  DMFT/src/main/java/com/gov/rsi/DMFT/DmftApplication.java
  DMFT/src/main/java/com/gov/rsi/DMFT/controllers/AbstractController.java
  DMFT/src/main/java/com/gov/rsi/DMFT/controllers/ReportController.java
  DMFT/src/main/java/com/gov/rsi/DMFT/models/Report.java
  DMFT/src/main/java/com/gov/rsi/DMFT/repositories/ReportRepository.java
  DMFT/src/main/java/com/gov/rsi/dmft/ApplicationProperties.java
  DMFT/src/main/java/com/gov/rsi/dmft/controllers/DmerController.java
  DMFT/src/main/java/com/gov/rsi/dmft/models/Dmer.java
  DMFT/src/main/java/com/gov/rsi/dmft/repositories/DmerRepository.java
  DMFT/src/main/resources/application.properties
  DMFT/src/main/resources/log4j.properties
  DMFT/src/test/java/com/gov/rsi/DMFT/DmftApplicationTests.java
Labels: enhancement

#7 DevOps OpenShift Integration
  api/dotnet/README.md
  api/dotnet/Services/MongoService.cs
  openshift/jenkins/api/Jenkinsfile
  openshift/templates/api/dotnet/README.md
  openshift/templates/api/dotnet/build.yaml
  openshift/templates/api/dotnet/deploy.yaml
  openshift/templates/base-images/README.md
  openshift/templates/base-images/dotnetcore-3.1.yaml
  openshift/templates/base-images/mongodb.yaml
  openshift/templates/db/mongo/README.md
  openshift/templates/db/mongo/deploy.yaml
  openshift/templates/network/network-security-policy.yaml
  openshift/templates/pipeline/api-pipeline.yaml
Labels: enhancement

#8 Fixing bug with env var name.
  api/dotnet/Services/MongoService.cs
Labels: bug

#9 Adding debug statement to figure out why OpenShift is not working.
  api/dotnet/Services/MongoService.cs
  api/dotnet/appsettings.json
Labels: bug

#11 Merging Robert's latest code. Fixing API to support PHSA.
  DMFT/src/main/java/com/gov/rsi/DMFT/controllers/AbstractController.java
  DMFT/src/main/java/com/gov/rsi/dmft/ApplicationProperties.java
  DMFT/src/main/java/com/gov/rsi/dmft/controllers/DmerController.java
  DMFT/src/main/java/com/gov/rsi/dmft/models/Dmer.java
  DMFT/src/main/java/com/gov/rsi/dmft/repositories/DmerRepository.java
  DMFT/src/main/resources/log4j.properties
  api/dotnet/Controllers/DmerController.cs
  api/dotnet/Helpers/Json/JsonParser.cs
  api/dotnet/Models/Queue.cs
  api/dotnet/Services/MongoService.cs
  api/dotnet/appsettings.Development.json
  api/java/Dockerfile
  api/java/pom.xml
  api/java/src/main/java/com/gov/rsi/dmft/ApplicationProperties.java
  api/java/src/main/java/com/gov/rsi/dmft/DmftApplication.java
  api/java/src/main/java/com/gov/rsi/dmft/MongoDbConfiguration.java
  api/java/src/main/java/com/gov/rsi/dmft/controllers/AbstractController.java
  api/java/src/main/java/com/gov/rsi/dmft/controllers/DmerController.java
  api/java/src/main/java/com/gov/rsi/dmft/models/Dmer.java
  api/java/src/test/java/com/gov/rsi/DMFT/DmftApplicationTests.java
  docker-compose.yaml
Labels: bug, enhancement

#12 Fixing 204 issue and adding Delete.
  api/dotnet/Controllers/DmerController.cs
Labels: bug, enhancement

#14 Fixing PUT. Adding table endpoint.
  api/dotnet/Controllers/DmerController.cs
  api/dotnet/Helpers/Json/JsonParser.cs
  api/dotnet/Models/Dmer.cs
  api/dotnet/Services/MongoService.cs
  api/dotnet/Startup.cs
  api/dotnet/Views/Dmer/QueueTable.cshtml
  api/dotnet/wwwroot/css/tables.css
Labels: bug, enhancement

#13 RPA processes implemented for Sprint2
  DMFT-RPA/DMFT1-Sprint2.1.bprelease
Labels: enhancement
